# general aliases
alias ll="ls -la"
alias v="f -e vim"

# fasd at startup
eval "$(fasd --init auto)"

# start vim mode
set -o vi

# set prompt
export PS1="\[\e[31m\]>\[\e[m\] \[\e[36m\]\w\[\e[m\]\\$ "

